# This is a sample build configuration for all languages.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: dancinllama/dockerdx

pipelines:
  branches:
    stage:
      - step:
          script:
          - echo "Authenticating with hub org"
          - sfdx force:auth:jwt:grant --clientid $CONSUMER_KEY --jwtkeyfile assets/server.key --username $USERNAME --setdefaultdevhubusername -a dxhub
    prod:
      - step:
          script:
          - echo "In Prod"
